### PR TITLE
Add docker-compose with a script to start the application

### PR DESCRIPTION
**Pull request by FlorentMetz**
Hi, saw your post on Reddit and decided to checkout your repository.

I am more of a Symfony developer and I always meant to look at Laravel so wanted to dig into heroes profile but I found the setup a bit messy.

This first PR is mostly to ask questions and add a simple docker-compose.yml for local development with docker.

TL;DR: run `./create-local-docker.sh` which will run 2 docker containers; the application HeroesProfile with your Dockerfile and a database with mariadb (that can be easily changed to MySQL).

I also created a new folder called "os-conf" where I put a couple of files. The reason is that I find it clearer to separate Laravel with the "devops" (You use apache2 but maybe later you'll move on to nginx)

- Would you have a backed up database - or at least a schema so we could actually work with something other than the models?
- Why is there a mysql connection for each database? Do you actually have 7 different databases with 7 different connections as per your `conf/database.php`? It would be easier to have one connection to 7 databases or even just 1 connection to 1 database and all your tables in there but that's up to you.
- Are there other services to be aware of? (Notification, emails, Queue, Redis, cron?)

Anyway - I'd be happy to help more :)

### CODE REVIEW

**Comment by FlorentMetz** [comment]
Also, looks like I resolved https://github.com/Heroes-Profile/heroesprofile/issues/254 by not using the setup script which is deprecated in node 20

**Comment by Zemill** [comment]
> Would you have a backed up database - or at least a schema so we could actually work with something other than the models?
I can look into this.  I was waiting until someone actually wanted it before pulling something together

> Why is there a mysql connection for each database? Do you actually have 7 different databases with 7 different connections as per your conf/database.php? It would be easier to have one connection to 7 databases or even just 1 connection to 1 database and all your tables in there but that's up to you.
There are 7 schemas.  I set this up 5 years ago and my focus hasn't been on modifying the database.  I have a table called replays, and then we have esport data, so in the esport data is another table called replays.  If I put it all into 1 connection, then I am not sure how would set up the model for replays as it wouldn't know which schema to go after.  

`Are there other services to be aware of? (Notification, emails, Queue, Redis, cron?`
https://github.com/Heroes-Profile/heroesprofile/blob/develop/.env.example has references to the required items.  In short, battlenet keys, patreon keys, and then an email forwarder.  No queues, redis, crons, notifications etc.

**Comment by Zemill** [comment]
> your Dockerfile and a database with mariadb (that can be easily changed to MySQL).

Any reason you would need the mariadb or mysql database?  Currently I connect to my database through a proxy, so the database doesnt live with the docker image/website at all

**Comment by Zemill** [comment]
> The database in the docker-compose file is purely for developing locally. If you provide me with a database schema (I don't need the content, just the structure) then I can create a laravel migration as well.
> 
> docker-compose is great for everyone to have a quick starting point to develop on your app - because at the moment we can't load anything since there is no database and Laravel expects a database. So it's difficult to help you develop the website :)

I was thinking about this after I wrote it and figured that might be the case.  I will work on the laravel table migrations.  I actually have the code for that written somewhere from a previous iteration of this

**Comment by Zemill** [comment]
Will reassess this at a later time

**Pull request closed without merging**
